### ISSUE TITLE
已经爬去不了了，怎么进行更新？

### ISSUE THREAD

**Issue by changshuangzhao** [kong36088/BaiduImageSpider#12]
Traceback (most recent call last):
  File "index.py", line 140, in <module>
    crawler.start('树',100,1)
  File "index.py", line 131, in start
    self.get_images(word)
  File "index.py", line 111, in get_images
    rsp_data = json.loads(rsp)
  File "/home/ch/anaconda3/envs/py3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/home/ch/anaconda3/envs/py3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/ch/anaconda3/envs/py3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Athenanna** [comment]
同，请作者修复，请作者吃糖，感恩

**Comment by kong36088** [comment]
直观上感觉是百度把接口下掉了 或 接口回包格式改了。
平常工作比较忙，周末我抽空升级下

**Comment by Scorpionmayong** [comment]
老哥,我也遇到这个问题.

**Comment by kong36088** [comment]
> Traceback (most recent call last):
> File "index.py", line 140, in
> crawler.start('树',100,1)
> File "index.py", line 131, in start
> self.get_images(word)
> File "index.py", line 111, in get_images
> rsp_data = json.loads(rsp)
> File "/home/ch/anaconda3/envs/py3/lib/python3.6/json/**init**.py", line 354, in loads
> return _default_decoder.decode(s)
> File "/home/ch/anaconda3/envs/py3/lib/python3.6/json/decoder.py", line 339, in decode
> obj, end = self.raw_decode(s, idx=_w(s, 0).end())
> File "/home/ch/anaconda3/envs/py3/lib/python3.6/json/decoder.py", line 357, in raw_decode
> raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

已支持新版接口
