### ISSUE TITLE
最后一段代码执行不了？问题如下：

### ISSUE THREAD

**Issue by Louischeeron** [kong36088/BaiduImageSpider#16]
usage: ipykernel_launcher.py [-h] -w WORD -tp TOTAL_PAGE -sp START_PAGE
                             [-pp [{10,20,30,40,50,60,70,80,90,100}]]
                             [-d DELAY]
ipykernel_launcher.py: error: the following arguments are required: -w/--word, -tp/--total_page, -sp/--start_page
An exception has occurred, use %tb to see the full traceback.

SystemExit: 2
这是为啥？

**Comment by kong36088** [comment]
ipykernel_launcher.py

**Comment by kong36088** [comment]
ipykernel_launcher.py

这个是你自己修改的代码么？项目里提供的不是这个文件
