### ISSUE TITLE
看起来失效了，用不起来

### ISSUE THREAD

**Issue by futureflsl** [kong36088/BaiduImageSpider#19]
看起来失效了，用不起来

**Comment by dongdongrj** [comment]
是的，去年还可以用。现在用老是报错

**Comment by nsplnpbjy** [comment]
我也是KeyError: 'data'

**Comment by kong36088** [comment]
百度升级了反爬虫机制。
已更新代码，现在爬虫能继续正常使用了 @futureflsl @dongdongrj @nsplnpbjy
