### ISSUE TITLE
你好，之前爬虫没问题，最近好像失效了，报错如下图所示

### ISSUE THREAD

**Issue by bitwangdan** [kong36088/BaiduImageSpider#21]
![image](https://user-images.githubusercontent.com/18326564/115978072-bcc7c280-a5af-11eb-9dea-f675ba4930b3.png)
请问可以帮忙看下嘛？麻烦你了

**Comment by kong36088** [comment]
百度升级了反爬虫机制。已更新代码，现在爬虫能继续正常使用了

**Comment by kong36088** [comment]
百度升级了反爬虫机制。
已更新代码，现在爬虫能继续正常使用了  @bitwangdan
