### ISSUE TITLE
json.decoder.JSONDecodeError: Invalid \escape: line 12 column 145 (char 30889)

### ISSUE THREAD

**Issue by suke27** [kong36088/BaiduImageSpider#24]
Hi, great jobs
when i check issue history, it seems you have resolved this issue, but when i try to run it, i also meet this issue.
could you check it. Thanks

**Comment by kong36088** [comment]
@suke27 Please provide the problem case, so that I can reproduce the bug.

**Comment by TiankaiHang** [comment]
> @suke27 Please provide the problem case, so that I can reproduce the bug.

@kong36088 I met the problem using this command line
`python crawling.py -tp 10 -sp 1 -w "dog"`

**Comment by kong36088** [comment]
already fixed
