### ISSUE TITLE
疑问，求解

### ISSUE THREAD

**Issue by xiaoyu827** [kong36088/BaiduImageSpider#28]
下载到了空文件，跳过!
下载到了空文件，跳过
下载到了空文件，跳过!
Remote end closed connection without response
产生未知错误，放弃保存

以上是问题，总是下载到了空文件，pc可以，但是termux进行就会这个问题，无root，请问怎么解决

**Comment by xiaoyu827** [comment]
感觉是ip被封了

**Comment by kong36088** [comment]
@2015077314 被封了（反爬策略）。爬数据本身是一个和官方斗智斗勇的过程 :)

**Comment by xiaoyu827** [comment]
> @2015077314 被封了（反爬策略）。爬数据本身是一个和官方斗智斗勇的过程 :)
用代理软件换个ip就行，我用代理池把你的脚本更新一下，在提交一下，可以不

**Comment by kong36088** [comment]
> > @2015077314 被封了（反爬策略）。爬数据本身是一个和官方斗智斗勇的过程 :)
> > 用代理软件换个ip就行，我用代理池把你的脚本更新一下，在提交一下，可以不

@2015077314 那个是你自己个人的代理池吧，就不放到项目里面了。本项目主要还是给大家提供一个简单开箱即用的工具。

**Comment by xiaoyu827** [comment]
> > > @2015077314 被封了（反爬策略）。爬数据本身是一个和官方斗智斗勇的过程 :)
> > > 用代理软件换个ip就行，我用代理池把你的脚本更新一下，在提交一下，可以不
> 
> @2015077314 那个是你自己个人的代理池吧，就不放到项目里面了。本项目主要还是给大家提供一个简单开箱即用的工具。

好吧https://jhao104.github.io/proxy_pool/，这个也是别人开源的，挺好用的
