### ISSUE TITLE
下载下一页触发后，抛出UnicodeDecodeErrorurl

### ISSUE THREAD

**Issue by maple5233** [kong36088/BaiduImageSpider#4]
RT

-----UnicodeDecodeErrorurl: http://image.baidu.com/search/avatarjson?tn=resultjsonavatarnew&ie=utf-8&word=%E8%A1%80%E5%B8%B8%E8%A7%84&cg=girl&pn=180&rn=60&itg=0&z=0&fr=&width=&height=&lm=-1&ic=0&s=0&st=-1&gsm=1e0000001e

pn 突然从0到了180

**Comment by kong36088** [comment]
UnicodeDecode的问题确实是bug，这里最新代码已解决上述问题。
pn的问题可能是你程序入口设置的页码问题。若调用方式为：crawler.start('血常规', 3, 3)，pn便会出现你上述描述的情况。
