### ISSUE TITLE
大佬 请问能抓高清的图片吗

### ISSUE THREAD

**Issue by YuzhouPeng** [kong36088/BaiduImageSpider#9]
如题 非常感谢

**Comment by chuang-zhi** [comment]
可以抓取，但是目前要修改代码（height和width）

**Comment by YuzhouPeng** [comment]
好的，非常感谢

**Comment by wwdok** [comment]
请问如何修改呢，我看代码里有一处含有height的地方
![image](https://user-images.githubusercontent.com/43233772/106376172-9ab60e00-63cd-11eb-978c-8b0d515f4b1f.png)
